# Setup
title: Mohammed Louai Alayoubi
#logo: 
#description: text below image
show_downloads: true
theme: jekyll-theme-minimal

# About
author:
  name:    Mohammed Louai Alayoubi
  url:     https://louai20.github.io/ 
  email:   loieayoubi@gmail.com


# Custom vars
version:             2.0.1
github:
  repo:              https://louai20.github.io/ 
linkedin_username::  Mohammed Louai Alayoubi
  
